spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/user2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ENC@(MIJueAfnYWsKa2kiR8Qrrw==)
    password: ENC@(qH9m5vjj8RYULOASKdhlOw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
jasypt:
  encryptor:
    # 配置加密算法
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    property:
      # 算法识别前缀(当算法发现配置文件中的值以这前缀开始，后缀结尾时，会使用指定算法解密)
      prefix: ENC@(
      # 算法识别后缀
      suffix: )
    password: ${JASYPT_ENCRYPTOR_PASSWORD}